version: '3.0'

services:

  lamp:
    image: alpine:latest
    container_name: ${APP_NAME}-lamp
    depends_on:
      - httpd
      - php
      - mariadb
    networks:
      - back

  lemp:
    image: alpine:latest
    container_name: ${APP_NAME}-lemp
    depends_on:
      - nginx
      - php
      - mariadb
    networks:
      - back

  nginx:
    image: nginx
    container_name: ${APP_NAME}-nginx
    depends_on:
      - php
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "${HTTP_PORT}:80"
    environment:
      NGINX_HOST: ${HTTP_HOST}
    networks:
      - front
      - back

  httpd:
    image: httpd:${HTTPD_VERSION} 
    container_name: ${APP_NAME}-httpd
    depends_on:
      - php
    volumes:
      - ./etc/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./etc/httpd/conf.d:/usr/local/apache2/conf/conf.d
      - ./src:/var/www/html
    ports:
      - "${HTTP_PORT}:80"
    environment:
      HTTP_HOST: ${HTTP_HOST}
    networks:
      - front
      - back

  php:
    build:
      context: ./etc/php
      args:
        VERSION: ${PHP_VERSION}
    container_name: ${APP_NAME}-php
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    networks:
      - back
  
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${APP_NAME}-mariadb
    volumes:
      - ./etc/mariadb/conf.d:/etc/mysql/conf.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - back

  mongodb:
    image: mongo:${MONGODB_VERSION}
    container_name: ${APP_NAME}-mongodb
    volumes:
      - ./data/mongodb:/data/db
      - ./etc/mongo/initdb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_APP_DATABASE: ${MONGODB_DATABASE}
      MONGO_APP_USERNAME: ${MONGODB_USERNAME}
      MONGO_APP_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_APP_ROLE: 'dbOwner'
    networks:
      - back

  mongo-express:
    image: mongo-express
    container_name: ${APP_NAME}-mongo-express
    depends_on:
      - mongodb
    ports:
      - "${MONGODB_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGODB_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - back

  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    depends_on:
      - mariadb
    ports:
      - "${MARIADB_ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - back

  express:
    build:
      context: ./etc/express
      args:
        VERSION: ${NODE_VERSION}
    container_name: ${APP_NAME}-express
    ports:
      - "${HTTP_PORT}:3000"
    volumes:
      - ./src:/app
    environment:
      EXPRESS_VIEW_ENGINE: pug
      EXPRESS_STYLE_ENGINE: sass
    networks:
      - front
      - back

  strapi:
    image: strapi/strapi
    container_name: ${APP_NAME}-strapi
    depends_on:
      - mongodb
    ports:
      - "${STRAPI_PORT}:1337"
    volumes:
      - ./data/strapi:/usr/src/api/strapi-app
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_NAME: ${MONGODB_DATABASE}
      DATABASE_USERNAME: ${MONGODB_USERNAME}
      DATABASE_PASSWORD: ${MONGODB_PASSWORD}
      DATABASE_AUTHENTICATION_DATABASE: ${MONGODB_DATABASE}
      DATABASE_SSL: 'false'
    networks:
      - front
      - back

networks:
  front:
  back: