version: '3.0'

services:

  lamp:
    image: alpine:latest
    container_name: ${APP_NAME}-lamp
    depends_on:
      - httpd
      - php
      - mariadb
    networks:
      - back

  lemp:
    image: alpine:latest
    container_name: ${APP_NAME}-lemp
    depends_on:
      - nginx
      - php
      - mariadb
    networks:
      - back

  nginx:
    image: nginx
    container_name: ${APP_NAME}-nginx
    depends_on:
      - php
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - ${HTTP_PORT}:80
    environment:
      - NGINX_HOST=${HTTP_HOST}
    networks:
      - front
      - back

  httpd:
    image: httpd:${HTTPD_VERSION} 
    container_name: ${APP_NAME}-httpd
    depends_on:
      - php
    volumes:
      - ./etc/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./etc/httpd/conf.d:/usr/local/apache2/conf/conf.d
      - ./src:/var/www/html
    ports:
      - ${HTTP_PORT}:80
    environment:
      - HTTP_HOST=${HTTP_HOST}
    networks:
      - front
      - back

  php:
    build:
      context: ./etc/php
      args:
        VERSION: ${PHP_VERSION}
    container_name: ${APP_NAME}-php
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    networks:
      - back
  
  mariadb:
    image: mariadb:${DB_VERSION}
    container_name: ${APP_NAME}-mariadb
    volumes:
      - ./etc/mariadb/conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - back

  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    depends_on:
      - mariadb
    ports:
      - ${DB_ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - back

networks:
  front:
  back: